from enum import Enum

class TokenType(Enum):
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE = range(0, 10)
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR = range(10, 20)
    BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL = range(20, 30)
    IDENTIFIER, STRING, NUMBER = range(30, 40)
    AND, CLASS, ELSE, FALSE, FUN, FOR, IF, NIL = range(40, 50)
    OR, PRINT, RETURN, SUPER, THIS, TRUE, VAR, WHILE, EOF = range(50, 60)
